# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "https://mklabs.github.io"
port: 3000

source:      .
destination: ./_site

title: mklabs.github.io
description: "@mklabs website"

lang: 'fr'
permalink: 'articles/:title/'

kramdown:
  input: GFM
  hard_wrap: false

# exclude - a list of fileglob patterns from the conversion
exclude:
  - 'node_modules/**/*'
  # - 'articles/**/*.js'

# layout - if set, will use this layout as default one when no config is
# found in the front yaml/json config.
layout: 'post'

pages: &pages
  files:
    - '*.html'
    - 'feed/index.xml'
    - '**/*.md'
    - '**/*.markdown'
    - 'examples/**/*.js'

paginate: 7

# redirect homepage to about
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
